Repository virtool/virtool, pull requests merged in 2020-10, with the labels that each got.

#1910 Migration
  tests/analyses/test_migrate.py
  tests/db/test_migrate.py
  tests/db/test_utils.py
  tests/files/test_migrate.py
  tests/groups/test_migrate.py
  tests/references/test_migrate.py
  tests/samples/test_migrate.py
  tests/subtractions/test_migrate.py
  virtool/analyses/migrate.py
  virtool/caches/migrate.py
  virtool/db/migrate.py
  virtool/db/utils.py
  virtool/files/migrate.py
  virtool/groups/migrate.py
  virtool/jobs/migrate.py
  virtool/references/migrate.py
  virtool/samples/migrate.py
  virtool/subtractions/migrate.py
  virtool/users/migrate.py
  virtool/utils.py
Labels: Backend, Improvement

#1911 Docstring & typing for virtool.jobs.analysis
  virtool/jobs/analysis.py
Labels: Backend

#1919 Fix theme lookup in OTU form module
  client/src/js/otus/components/Form.js
Labels: Bug, Frontend

#1924 Install dnspython package
  requirements.txt
Labels: Backend, Bug

#1926 Wait for another job if a compatible cache is being created
  tests/jobs/test_utils.py
  virtool/jobs/utils.py
Labels: Backend, Bug

#1931 Add docstrings, typings, and TODOs to virtool.jobs.caching
  virtool/jobs/caching.py
Labels: Backend

#1922 Add task for generating FASTA files
  virtool/app.py
  virtool/startup.py
  virtool/subtractions/db.py
  virtool/tasks/steps.py
Labels: Backend
